### ISSUE TITLE
Account session control

### ISSUE THREAD

**Issue by dmitrytavern** [bidaro-open-source/bidaro#7]
Every refresh session has metadata as the value of the key.

Session metadata:

- `uuid` - session-id
- `uid` - user-id
- `ua`  - user agent
- `ip` - ip address
- `created_at` - the date when the session is created

## Getting active sessions

For getting all active user sessions, use `GET /auth/sessions`.

Response from getting sessions:

```
[{ uuid: string, ua: string, ip: string, created_at: string }]
```

But, the server doesn't send refresh tokens in the response. Instead, the server sends the `uuid` of the refresh session. 

## Deleting an active session(s)

To delete the session by uuid, use `DELETE /auth/sessions`

To clear all sessions except current ones pass a list of uuid.

## Tasks

- [ ] Add collection metadata to refresh sessions
- [ ] Add `GET /user/${ID}/sessions`
- [ ] Add `DELETE /user/${ID}/sessions`
